import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';

// Load env (prefer .env.local if present)
const envLocal = path.resolve(process.cwd(), '.env.local');
if (fs.existsSync(envLocal)) {
    dotenv.config({ path: envLocal });
}
dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

function normalize(str: string) {
    if (!str) return '';
    return str
        .toLowerCase()
        .replace(/[\u2018\u2019\u00B4\u02BB\u02BC\u02BF\u02BE]/g, "'")
        .replace(/['`]/g, '')
        .replace(/(viloyati|viloyat|tumani|tuman|shahri|shahar|respublikasi|respublika)/g, '')
        .replace(/\s+/g, '')
        .trim();
}

async function generateMap() {
    console.log('Fetching local dictionary...');
    const { data: regions } = await supabase.from('regions').select('id, name_uz');
    const { data: districts } = await supabase.from('districts').select('id, name_uz, region_id');

    if (!regions || !districts) throw new Error('Failed to fetch local dict');

    const regionsById = new Map(regions.map(r => [String(r.id), r]));
    const districtsById = new Map(districts.map(d => [String(d.id), d]));

    console.log('Fetching OsonIsh jobs location data...');

    const { data: jobs } = await supabase
        .from('jobs')
        .select('raw_source_json')
        .eq('source', 'osonish')
        .limit(5000);

    if (!jobs) throw new Error('No jobs');

    const osonishRegions = new Map<string, string>();
    const osonishDistricts = new Map<string, string>();

    jobs.forEach(job => {
        const r = job.raw_source_json?.filial?.region;
        const d = job.raw_source_json?.filial?.city;

        if (r?.id) osonishRegions.set(String(r.id), r.name_uz || r.name_ru || '');
        if (d?.id) osonishDistricts.set(String(d.id), d.name_uz || d.name_ru || '');
    });

    console.log(`Found ${osonishRegions.size} distinct OsonIsh regions`);
    console.log(`Found ${osonishDistricts.size} distinct OsonIsh districts`);

    const regionMap: Record<string, string> = {};
    const districtMap: Record<string, string> = {};

    console.log('\n--- REGION MAPPING ---');
    for (const [id, name] of Array.from(osonishRegions.entries())) {
        // Prefer direct ID match if region exists
        const direct = regionsById.get(id);
        if (direct) {
            regionMap[id] = direct.id;
            continue;
        }

        const normName = normalize(name);
        const match = regions.find(r => normalize(r.name_uz) === normName);
        if (match) {
            regionMap[id] = match.id;
        } else {
            console.log(`NO MATCH FOR REGION: ${id} - ${name}`);
        }
    }

    console.log('\n--- DISTRICT MAPPING ---');
    for (const [id, name] of Array.from(osonishDistricts.entries())) {
        // Prefer direct ID match if district exists
        const direct = districtsById.get(id);
        if (direct) {
            districtMap[id] = direct.id;
            continue;
        }

        const normName = normalize(name);
        const match = districts.find(d => normalize(d.name_uz) === normName);
        if (match) {
            districtMap[id] = match.id;
        } else {
            const semiMatch = districts.find(d => {
                const norm = normalize(d.name_uz);
                return norm.includes(normName) || normName.includes(norm);
            });
            if (semiMatch) {
                districtMap[id] = semiMatch.id;
                console.log(`Fuzzy match: ${name} -> ${semiMatch.name_uz}`);
            } else {
                console.log(`NO MATCH FOR DISTRICT: ${id} - ${name}`);
            }
        }
    }

    console.log(`\nWriting to lib/mappers/osonish-locations.ts...`);

    const fileContent = `/**
 * STRICT LOCATION MAPPING (Generated by scripts/generate-location-map.ts)
 * OsonIsh ID -> ISHDASIZ ID
 */

export const OSONISH_REGION_MAP: Record<string, number> = ${JSON.stringify(regionMap, null, 4)};

export const OSONISH_DISTRICT_MAP: Record<string, number> = ${JSON.stringify(districtMap, null, 4)};
`;

    fs.writeFileSync(path.join(process.cwd(), 'lib/mappers/osonish-locations.ts'), fileContent);
    console.log('Done!');
}

generateMap().catch(console.error);
