
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

// Load env from root
dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

function normalize(str: string) {
    return str.toLowerCase()
        .replace(/[''`’‘]/g, '')
        .replace(/viloyati/g, '')
        .replace(/tumani/g, '')
        .replace(/shahri/g, '')
        .replace(/shahar/g, '')
        .replace(/respublikasi/g, '')
        .replace(/ /g, '')
        .trim();
}

async function generateMap() {
    console.log('Fetching local dictionary...');
    const { data: regions } = await supabase.from('regions').select('id, name_uz');
    const { data: districts } = await supabase.from('districts').select('id, name_uz, region_id');

    if (!regions || !districts) throw new Error('Failed to fetch local dict');

    console.log('Fetching OsonIsh jobs location data...');
    // We fetch distinct pairs of (id, name) from raw json
    // Since we can't do DISTINCT on json fields easily in API, we fetch all and aggregate in JS
    // Actually we can use the rpc/query via raw sql if needed, but let's just fetch simplified subset

    // Using simple approach: fetch 5000 records (should cover all variations)
    const { data: jobs } = await supabase
        .from('jobs')
        .select('raw_source_json')
        .eq('source', 'osonish')
        .limit(5000);

    if (!jobs) throw new Error('No jobs');

    const osonishRegions = new Map<string, string>(); // id -> name
    const osonishDistricts = new Map<string, string>(); // id -> name

    jobs.forEach(job => {
        const r = job.raw_source_json?.filial?.region;
        const d = job.raw_source_json?.filial?.city;

        if (r?.id) osonishRegions.set(String(r.id), r.name_uz || r.name_ru);
        if (d?.id) osonishDistricts.set(String(d.id), d.name_uz || d.name_ru);
    });

    console.log(`Found ${osonishRegions.size} distinct OsonIsh regions`);
    console.log(`Found ${osonishDistricts.size} distinct OsonIsh districts`);

    const regionMap: Record<string, string> = {};
    const districtMap: Record<string, string> = {};

    // Match Regions
    console.log('\n--- REGION MAPPING ---');
    for (const [id, name] of Array.from(osonishRegions.entries())) {
        const normName = normalize(name);
        // Try strict name match
        const match = regions.find(r => normalize(r.name_uz) === normName);
        if (match) {
            regionMap[id] = match.id;
            // console.log(`✅ ${name} -> ${match.name_uz}`);
        } else {
            console.log(`❌ NO MATCH FOR REGION: ${id} - ${name}`);
            // Manual fallbacks can be added here
        }
    }

    // Match Districts
    console.log('\n--- DISTRICT MAPPING ---');
    for (const [id, name] of Array.from(osonishDistricts.entries())) {
        const normName = normalize(name);
        // Try match
        const match = districts.find(d => normalize(d.name_uz) === normName);
        if (match) {
            districtMap[id] = match.id;
        } else {
            // Try simplified match (contains)
            const semiMatch = districts.find(d => normalize(d.name_uz).includes(normName) || normName.includes(normalize(d.name_uz)));
            if (semiMatch) {
                districtMap[id] = semiMatch.id;
                console.log(`⚠️ Fuzzy match: ${name} -> ${semiMatch.name_uz}`);
            } else {
                console.log(`❌ NO MATCH FOR DISTRICT: ${id} - ${name}`);
            }
        }
    }


    console.log(`\nWriting to lib/mappers/osonish-locations.ts...`);

    const fileContent = `/**
 * STRICT LOCATION MAPPING (Generated by scripts/generate-location-map.ts)
 * OsonIsh ID -> ISHDASIZ ID
 */

export const OSONISH_REGION_MAP: Record<string, number> = ${JSON.stringify(regionMap, null, 4)};

export const OSONISH_DISTRICT_MAP: Record<string, number> = ${JSON.stringify(districtMap, null, 4)};
`;

    const fs = require('fs');
    fs.writeFileSync(path.join(process.cwd(), 'lib/mappers/osonish-locations.ts'), fileContent);
    console.log('Done!');
}

generateMap().catch(console.error);
