/**
 * STRICT LOCATION MAPPING (Generated by scripts/generate-location-map.ts)
 * OsonIsh ID -> ISHDASIZ ID
 */

// NOTE:
// OsonIsh numeric IDs are NOT aligned with ISHDASIZ DB IDs.
// Using a static map causes wrong region/district assignments.
// Runtime name-based mapping (with SOATO + normalized names) is used instead.
export const OSONISH_REGION_MAP: Record<string, number> = {};
export const OSONISH_DISTRICT_MAP: Record<string, number> = {};
